### ISSUE TITLE
Traceback (most recent call last):   File "yolov8_deepsort_trt.py", line 145, in <module>     main(args)   File "yolov8_deepsort_trt.py", line 83, in main     bboxes, scores, labels = det_postprocess(data)   File "/home/nvidia/gxq_files/YOLOv8_Object_Tracking_TensorRT-main/srcs/models/torch_utils.py", line 63, in det_postprocess     assert len(data) == 4 AssertionError ------------------------------------------------------------------- PyCUDA ERROR: The context stack was not empty upon module cleanup. ------------------------------------------------------------------- A context was still active when the context stack was being cleaned up. At this point in our execution, CUDA may already have been deinitialized, so there is no way we can finish cleanly. The program will be aborted now. Use Context.pop() to avoid this problem.有两个错误可以给解答以下吗？

### ISSUE THREAD

**Issue by 1204Gin** [nabang1010/YOLOv8_Object_Tracking_TensorRT#6]

**Comment by nabang1010** [comment]
@1204Gin Can you check your `torch` is compatative with `CUDA` ? Please give me your `torch` and `CUDA` version ?
